language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

notifications:
  on_success: change
  on_failure: always
  slack:
    secure: pDs0yYkoNveNbAp34Be2RIjfsGxy4UYzjF4xXqWdI2c0KribDl81gi864OYSeUUgOhAoTXKCqSL4yz6ULk7zA0FnEk2oeruPbGd31LaXNV/8t07rjEKHX4vuw+KfDMi6mgvNzZM7783jJ5+B8N8YoU2dLeFZG6beo+giA8u8e8eZp89LHJis00AG7WS/Eur4C+gCteoMeKSSnQX36bPUnTn91NRzv75tkx0hCe7o7Au5Fg5v04iq2ilmSMD6pSKctQvq4tI0hxcFB7m/f6Uy101u2WEB9tbuBTeYHw3ZrS4aKvxSUr64r6M3LFGHR2iY4v1ZIVdTCK9NXSAa3rcg2rgbufbfvNASD9mciu/6NGu6iB6InkOk/D7UAExSko41uJTfENymEv0tfDK8PC9+mwVx9XbPwcIcW3exISlhjTxttpliXLP4wFjH3GAuJv8EnBM+QcpuFt1On83+p1kTXis4zk/7xLsbFGXvGiqmcrez/17jwdTGcjvAdwtRCc+vkCg5eEiv1mf4zLDtjlUlc3COBcr0pDRx3AWMwv4TXnRkvEpWCehOGuHYlecNZZJ4yZUKX1ehAFBza9J0kqUrrFzn4CKyys4KZ+XSKMKiVCamnlF1TEbOTK3l9I/W+5boP/PnZjwq++txVA+S4l/nxiZP0Ai1Ei5il4QGw0mfMrg=

after_success:
- Rscript -e 'covr::codecov()'
