language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

notifications:
  on_success: change
  on_failure: always
  slack:
    secure: "X8gr1NGq+gEChlRN7oXFzeRzuQhjTLq7eLHWlXf6nYMFTg30vIjoEp6TN6/hgzPL3fGPG4i8jV++RYAyN5L9Eq6NmPb6dhB/I4y6ssVDA3z4qyi0xNX2sxg2jrJbDwWRb7fuJCLO+T84tRvl8uod0bH29MPyUK9eyAaXghGx3wFaKdN0uRGRooWTWIc8SSQK4JgvzbsatKWo3J9KWGmZwhJ9rXqq47oheUzY//z7Pq2dZINbLA3ysiAxL6E4vB2eHIPQRNFZlTO55g/KAaVYfTd0ywPdsmozLqIbZwcZrczT0rLAnms/Ub0Nlw3sYLevbM+ER1k0qwhOkALy2aWn8CKiqzcG9Tsm1Tzyc7S+0ehD7WIJwSfa/VHVBDK9J98tE9M3syTS+SMGMcCVdmljXFDqO2/4ZoGtdPoPqnCJn61AszpDNOkGIE1PmCOvANwMRqti+9NlWGAlJ37bGcK+fZIcObh5eSzthqiYIeFF7+SsoCEwDi3lI0WMstj4dZzeSPwD6pXPSg3Mijv/k7uvxk2jFdonowW2YhMPjNn+khaaSPlGpAvDjK1NkBrBlCszs12GgInjZuPWcU5PXZDPe1qdsAD28sPVQZ33GWnAMABP54FcRklJeg3HFgd5A6LNKZ/khLmlLrGNa0Kv8iu4uk+gc2JLjyZzdpvQkscXWg8="
